#!/bin/bash
#chkconfig: 345 80 20
#       /etc/rc.d/init.d/

# Source function library.
. /etc/init.d/functions

start() {
        echo -n "Starting : "
	daemon ./home/testServer
        ps -ef|grep testServer|grep -v 'grep testServer' > /dev/null 2>&1
        if [[ $? == 1 ]]; then
	        echo -ne "Failed to start daemon \n"
        else
                echo -ne "Service started successfully.\n"
        fi
        return
}

stop() {
        echo -n "Shutting down : "
	#pid=`ps -ef|grep testServer|grep -v 'grep testServer'|awk '{print $2}'`
        #echo $pid
        killproc testServer
        if [[ $? != 0 ]]; then
            echo -ne "Failed to stop daemon \n"
        else
            echo -ne "daemon stopped successfully.\n"
        fi
        return
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|restart]"
        exit 1
        ;;
esac
exit $?

